-- ManifestHub forum schema for the existing Supabase project.
-- Non-destructive: creates forum-only objects and leaves existing tables intact.

BEGIN;

CREATE TABLE IF NOT EXISTS public.forum_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 40),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.forum_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id UUID NOT NULL REFERENCES public.forum_profiles(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('general', 'features', 'bugs', 'qa', 'tips')),
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 5 AND 140),
  content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 10000),
  score INTEGER NOT NULL DEFAULT 0,
  locked BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.forum_replies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.forum_posts(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES public.forum_replies(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.forum_profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 5000),
  score INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.forum_post_votes (
  post_id BIGINT NOT NULL REFERENCES public.forum_posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  value SMALLINT NOT NULL CHECK (value IN (-1, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.forum_reply_votes (
  reply_id BIGINT NOT NULL REFERENCES public.forum_replies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  value SMALLINT NOT NULL CHECK (value IN (-1, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (reply_id, user_id)
);

ALTER TABLE public.forum_replies
  DROP CONSTRAINT IF EXISTS forum_replies_parent_id_fkey;
ALTER TABLE public.forum_replies
  ADD CONSTRAINT forum_replies_parent_id_fkey
  FOREIGN KEY (parent_id) REFERENCES public.forum_replies(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_forum_posts_created_at
  ON public.forum_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_forum_posts_category
  ON public.forum_posts(category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_forum_replies_post
  ON public.forum_replies(post_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_forum_replies_parent
  ON public.forum_replies(parent_id);

CREATE OR REPLACE FUNCTION public.is_forum_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.admins
    WHERE lower(email) = lower(auth.jwt() ->> 'email')
  );
$$;

CREATE OR REPLACE FUNCTION public.get_forum_admin_ids(candidate_ids UUID[])
RETURNS TABLE(user_id UUID)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT DISTINCT users.id
  FROM auth.users AS users
  JOIN public.admins AS admins
    ON lower(admins.email) = lower(users.email)
  WHERE users.id = ANY(candidate_ids);
$$;

REVOKE ALL ON FUNCTION public.is_forum_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_forum_admin_ids(UUID[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_forum_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_forum_admin_ids(UUID[])
  TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.sync_forum_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  resolved_name TEXT;
BEGIN
  resolved_name := left(
    coalesce(
      nullif(trim(NEW.raw_user_meta_data ->> 'display_name'), ''),
      'Member'
    ),
    40
  );

  INSERT INTO public.forum_profiles (id, display_name)
  VALUES (NEW.id, resolved_name)
  ON CONFLICT (id) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        updated_at = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_forum_profile_trigger ON auth.users;
CREATE TRIGGER sync_forum_profile_trigger
AFTER INSERT OR UPDATE OF raw_user_meta_data, email ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.sync_forum_profile();

INSERT INTO public.forum_profiles (id, display_name)
SELECT
  id,
  left(
    coalesce(
      nullif(trim(raw_user_meta_data ->> 'display_name'), ''),
      'Member'
    ),
    40
  )
FROM auth.users
ON CONFLICT (id) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      updated_at = now();

CREATE OR REPLACE FUNCTION public.update_forum_post_score()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_id BIGINT;
  delta INTEGER;
BEGIN
  IF TG_OP = 'INSERT' THEN
    target_id := NEW.post_id;
    delta := NEW.value;
  ELSIF TG_OP = 'UPDATE' THEN
    target_id := NEW.post_id;
    delta := NEW.value - OLD.value;
  ELSE
    target_id := OLD.post_id;
    delta := -OLD.value;
  END IF;

  UPDATE public.forum_posts
  SET score = score + delta
  WHERE id = target_id;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_forum_reply_parent()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.forum_replies
    WHERE id = NEW.parent_id AND post_id = NEW.post_id
  ) THEN
    RAISE EXCEPTION 'Reply parent must belong to the same post';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.enforce_forum_post_cooldown()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW.author_id::text, 0));

  IF EXISTS (
    SELECT 1 FROM public.forum_posts
    WHERE author_id = NEW.author_id
      AND created_at > now() - interval '30 seconds'
  ) THEN
    RAISE EXCEPTION 'Please wait before creating another post';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.enforce_forum_reply_cooldown()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW.author_id::text, 0));

  IF EXISTS (
    SELECT 1 FROM public.forum_replies
    WHERE author_id = NEW.author_id
      AND created_at > now() - interval '10 seconds'
  ) THEN
    RAISE EXCEPTION 'Please wait before posting another reply';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_forum_reply_score()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_id BIGINT;
  delta INTEGER;
BEGIN
  IF TG_OP = 'INSERT' THEN
    target_id := NEW.reply_id;
    delta := NEW.value;
  ELSIF TG_OP = 'UPDATE' THEN
    target_id := NEW.reply_id;
    delta := NEW.value - OLD.value;
  ELSE
    target_id := OLD.reply_id;
    delta := -OLD.value;
  END IF;

  UPDATE public.forum_replies
  SET score = score + delta
  WHERE id = target_id;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS update_forum_post_score_trigger ON public.forum_post_votes;
CREATE TRIGGER update_forum_post_score_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.forum_post_votes
FOR EACH ROW EXECUTE FUNCTION public.update_forum_post_score();

DROP TRIGGER IF EXISTS update_forum_reply_score_trigger ON public.forum_reply_votes;
CREATE TRIGGER update_forum_reply_score_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.forum_reply_votes
FOR EACH ROW EXECUTE FUNCTION public.update_forum_reply_score();

DROP TRIGGER IF EXISTS validate_forum_reply_parent_trigger ON public.forum_replies;
CREATE TRIGGER validate_forum_reply_parent_trigger
BEFORE INSERT ON public.forum_replies
FOR EACH ROW EXECUTE FUNCTION public.validate_forum_reply_parent();

DROP TRIGGER IF EXISTS enforce_forum_post_cooldown_trigger ON public.forum_posts;
CREATE TRIGGER enforce_forum_post_cooldown_trigger
BEFORE INSERT ON public.forum_posts
FOR EACH ROW EXECUTE FUNCTION public.enforce_forum_post_cooldown();

DROP TRIGGER IF EXISTS enforce_forum_reply_cooldown_trigger ON public.forum_replies;
CREATE TRIGGER enforce_forum_reply_cooldown_trigger
BEFORE INSERT ON public.forum_replies
FOR EACH ROW EXECUTE FUNCTION public.enforce_forum_reply_cooldown();

ALTER TABLE public.forum_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_post_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_reply_votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Forum profiles are public" ON public.forum_profiles;
CREATE POLICY "Forum profiles are public"
  ON public.forum_profiles FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users update own forum profile" ON public.forum_profiles;
CREATE POLICY "Users update own forum profile"
  ON public.forum_profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Forum posts are public" ON public.forum_posts;
CREATE POLICY "Forum posts are public"
  ON public.forum_posts FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users create own forum posts" ON public.forum_posts;
CREATE POLICY "Users create own forum posts"
  ON public.forum_posts FOR INSERT
  WITH CHECK (auth.uid() = author_id);

DROP POLICY IF EXISTS "Users delete own forum posts" ON public.forum_posts;
DROP POLICY IF EXISTS "Owners and admins delete forum posts" ON public.forum_posts;
CREATE POLICY "Owners and admins delete forum posts"
  ON public.forum_posts FOR DELETE
  USING (auth.uid() = author_id OR public.is_forum_admin());

DROP POLICY IF EXISTS "Forum replies are public" ON public.forum_replies;
CREATE POLICY "Forum replies are public"
  ON public.forum_replies FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users create own forum replies" ON public.forum_replies;
CREATE POLICY "Users create own forum replies"
  ON public.forum_replies FOR INSERT
  WITH CHECK (
    auth.uid() = author_id
    AND EXISTS (
      SELECT 1 FROM public.forum_posts
      WHERE id = post_id AND locked = false
    )
  );

DROP POLICY IF EXISTS "Users delete own forum replies" ON public.forum_replies;
DROP POLICY IF EXISTS "Owners and admins delete forum replies" ON public.forum_replies;
CREATE POLICY "Owners and admins delete forum replies"
  ON public.forum_replies FOR DELETE
  USING (auth.uid() = author_id OR public.is_forum_admin());

DROP POLICY IF EXISTS "Users read own post votes" ON public.forum_post_votes;
CREATE POLICY "Users read own post votes"
  ON public.forum_post_votes FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users create own post votes" ON public.forum_post_votes;
CREATE POLICY "Users create own post votes"
  ON public.forum_post_votes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users update own post votes" ON public.forum_post_votes;
CREATE POLICY "Users update own post votes"
  ON public.forum_post_votes FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users delete own post votes" ON public.forum_post_votes;
CREATE POLICY "Users delete own post votes"
  ON public.forum_post_votes FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users read own reply votes" ON public.forum_reply_votes;
CREATE POLICY "Users read own reply votes"
  ON public.forum_reply_votes FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users create own reply votes" ON public.forum_reply_votes;
CREATE POLICY "Users create own reply votes"
  ON public.forum_reply_votes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users update own reply votes" ON public.forum_reply_votes;
CREATE POLICY "Users update own reply votes"
  ON public.forum_reply_votes FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users delete own reply votes" ON public.forum_reply_votes;
CREATE POLICY "Users delete own reply votes"
  ON public.forum_reply_votes FOR DELETE
  USING (auth.uid() = user_id);

GRANT SELECT ON public.forum_profiles, public.forum_posts, public.forum_replies
  TO anon, authenticated;

REVOKE INSERT, UPDATE, DELETE
  ON public.forum_profiles, public.forum_posts, public.forum_replies,
     public.forum_post_votes, public.forum_reply_votes
  FROM anon;

REVOKE UPDATE ON public.forum_profiles FROM authenticated;
GRANT UPDATE (display_name) ON public.forum_profiles TO authenticated;

REVOKE INSERT ON public.forum_posts, public.forum_replies FROM authenticated;
GRANT INSERT (author_id, category, title, content)
  ON public.forum_posts TO authenticated;
GRANT INSERT (post_id, parent_id, author_id, content)
  ON public.forum_replies TO authenticated;
GRANT DELETE ON public.forum_posts, public.forum_replies TO authenticated;

REVOKE INSERT, UPDATE
  ON public.forum_post_votes, public.forum_reply_votes
  FROM authenticated;
GRANT SELECT, DELETE
  ON public.forum_post_votes, public.forum_reply_votes
  TO authenticated;
GRANT INSERT (post_id, user_id, value)
  ON public.forum_post_votes TO authenticated;
GRANT INSERT (reply_id, user_id, value)
  ON public.forum_reply_votes TO authenticated;
GRANT UPDATE (value) ON public.forum_post_votes, public.forum_reply_votes
  TO authenticated;
REVOKE SELECT
  ON SEQUENCE public.forum_posts_id_seq, public.forum_replies_id_seq
  FROM authenticated;
GRANT USAGE
  ON SEQUENCE public.forum_posts_id_seq, public.forum_replies_id_seq
  TO authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';
